### ISSUE TITLE
Correct handling of patterns where slashes are in the spec?

### ISSUE THREAD

**Issue by robogeek** [Apollo314/openapi-to-zod#4]
The spec I'm using has specified some strings with a `pattern` field where the regular expression is delineated with slashes.  For example:

```yaml
    duration:
      type: string
      pattern: /^(-?)P(?=\d|T\d)(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)([DW]))?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$/
      description: duration in ISO 8601 format
      example: PT1H
      default: PT0S
```

I was not able to find if this is legitimate OpenAPI.  In the Swagger specification it shows a quoted string with no slashes, rather than an unquoted string with slashes like here.

The generated code for the above is:

```js
import { z } from "zod";

export default z
  .string()
  .regex(
    new RegExp(
      "/^(-?)P(?=\\d|T\\d)(?:(\\d+)Y)?(?:(\\d+)M)?(?:(\\d+)([DW]))?(?:T(?:(\\d+)H)?(?:(\\d+)M)?(?:(\\d+(?:\\.\\d+)?)S)?)?$/"
    )
  )
  .describe("duration in ISO 8601 format")
  .default("PT0S");
```

This fails on recognizing the string I fed it.  The RegExp object is defined (in MSDN) to take either a quoted string with no slashes, or an unquoted string with slashes.  The latter is directly recognized in JavaScript as a regular expression.

QUESTION:  Is an unquoted string with slashes allowed in OpenAPI to specify a regular expression?

If so, then this library should recognize that case, and pass through a RegExp literal.
