### ISSUE TITLE
Incorrect order for nullable/default

### ISSUE THREAD

**Issue by robogeek** [Apollo314/openapi-to-zod#5]
If an object schema has a field with `default: null` and `nullable: true`, the Zod schema is generated incorrectly.  The `.nullable()` appears after `.default(null)`, and `.default(null)` appears twice.

With this schema:

```yaml

components:
  schemas:
      hasDefaultNull:
        type: object
        properties:
          defaultNull:
            type: string
            format: date-time
            nullable: true
            default: null
      notNullable:
        type: object
        properties:
          defaultNull:
            type: string
            format: date-time
            # nullable: true
            default: null
```

Running the command:

```
$ npx openapi-to-zod -i ./nullable.yml -o zod -x ts
```

Generates these Zod schemas.

```
$ cat zod/zod-hasDefaultNull.ts 
import { z } from "zod";

export default z.object({
  defaultNull: z.string().datetime().default(null).nullable().default(null),
});

$ cat zod/zod-notNullable.ts 
import { z } from "zod";

export default z.object({ defaultNull: z.string().datetime().default(null) });
```

For the first `.default(null)`, with `tsconfig.json` containing `"strict": true`, an error is thrown by the compiler saying the following:

```
No overload matches this call.
  Overload 1 of 2, '(def: string): ZodDefault<ZodString>', gave the following error.
    Argument of type 'null' is not assignable to parameter of type 'string'.
  Overload 2 of 2, '(def: () => string): ZodDefault<ZodString>', gave the following error.
    Argument of type 'null' is not assignable to parameter of type '() => string'.ts(2769)
```

But, moving the `.nullable()` before `.default(null)` no such error is thrown.  THEORY, having `.nullable` first puts the Zod code into a state where `.default()` takes either `null | string` rather than just `string`.

The other issue is that `.default(null)` appears twice in the generated code.  This does not happen if `nullable` does not appear in the schema.
